### ISSUE TITLE
Should the default blueprint create the initial route/view structure?

### ISSUE THREAD

**Issue by begedin** [coderly/ember-gdrive#104]
Once configuration is properly set, a new ember-gdrive app doesn't really do anything. The user first needs to create the specific route structure that's needed by the add-on, followed by views/controllers/components.

This could technically all be done by the add-on's default blueprint. The only question is, should we do it and how far we should go. Here's my take on it, in order of progression:

## 1. Create the default route structure

This first step would be to modify the `Router`:

```JavaScript
Router.map(function() {
  this.resource('document', { path: 'd/:document_id' }, function() { });
  
  this.resource('login');
});
```

**The initial app would still look and run the same, but at least part of it would be prepared for the user.**

### `routes\application.js`:

```JavaScript
import Ember from 'ember';
import ApplicationRouteMixin from 'ember-gdrive/mixins/application-route-mixin';

export default Ember.Route.extend(ApplicationRouteMixin, {});
```

### `routes\document.js`:

```JavaScript
import AuthenticatedRouteMixin from 'ember-gdrive/mixins/authenticated-route-mixin';

export default Ember.Route.extend(AuthenticatedRouteMixin, {});
```

### `controllers\login.js`:

```JavaScript
import Ember from 'ember';
import LoginControllerMixin from 'ember-gdrive/mixins/login-controller-mixin';

export default Ember.Controller.extend(LoginControllerMixin, {});
```

### `templates\index.hbs`:

```Handlebars
{{#if session.isAuthenticated}}
  <a href="https://drive.google.com">Go to Google Drive</a>
  {{document-creator documentCreated='documentCreated'}}
{{else}}
  <h4>
      <button {{action 'login'}}>
          <span>Login with Google</span>
      </button>
  </h4>
{{/if}}
```

### `templates\login.hbs`:

```Handlebars
<button {{action 'authenticate'}}>Login with Google</button>
```

** By adding all of this, the user is immediately upon add-on installation able to log-in and create create new documents, which then navigates them to `document.index` of that document.**

**We could also add a share-modal component to a template somewhere, probably to `document.index`, so the user is able to share the document with others immediately.**

### `templates\error.hbs`:

```Handlebars
{{#if isAccessError}}
  <h1>That document does not exist</h1>

  <p>You may be logged in as the wrong user to access this document.</p>

  <a {{action 'logout'}} >Sign out and login as another user</a>
{{else}}
  <h1>Sorry, Something went wrong</h1>
  {{message}}
  <pre>
    {{stack}}
  </pre>
{{/if}}
```

** This one can really be made before option 2, but we'd have to remove the `lougou` button. In any case, I think adding automatic display of errors would be a good thing.**

### `controllers\error.js`:

```JavaScript
import Ember from 'ember';

var NOT_FOUND_REGEX = /The file was not found\. It does not exist or you do not have read access to the file\./;

export default Ember.ObjectController.extend({

  isAccessError: function(){
    var message = this.get('message');
    return (NOT_FOUND_REGEX.test(message));
  }.property('message')
});
```

Of course, all of these defaults would be subject to change. We could also add some default styling for some of this stuff, so there's a standardized look, like we did with the `share-modal`.

## 4. Also add a default example model, controller and view.

This is a stretch, but adding an example of a model, with functional crud operations might help the user figure things out, but I'm thinking this isn't necessary and if it is, it's probably more suitable as a separate blueprint the user can run manually.

**Comment by begedin** [comment]
On the note of number 4, we could create several blueprints for the other sections as well. The user could then generate the initial code themselves by running a blueprint command. This is still simpler than having to do it all manually, but it does at least provide an option instead of just doing it without question.

**Comment by venkatd** [comment]
I think doing all this without question is a good idea. We can provide scaffolding for a simple working app that they can then customize (or completely delete things). The scaffolding could just be a text box that multiple people can update with a share button.

How much effort is this idea?

**Comment by begedin** [comment]
Really not too much effort. Blueprints function in such a way that it's extremely easy to add files to the application. I'm not sure about how overwriting existing files works (in case of overwriting the router, for instance), but I'm sure something is available for that as well.

**Comment by venkatd** [comment]
Okay this sounds good to me.
