### ISSUE TITLE
Investigate (and potentially switch to) CollaborativeList in the context of using it in an ember adapter.

### ISSUE THREAD

**Issue by begedin** [coderly/ember-gdrive#21]
Since udates to the google drive API tend to break things in ember-gdrive (see #18), it might be a good idea to switch to a CollaborativeList for change tracking in a document and incorporate that in our ember-gdrive adapter.

https://developers.google.com/drive/realtime/reference/gapi.drive.realtime.CollaborativeList

This probably requires some investigation and planning before we implement it.

_I keep going back to this comment to make sure I'm understanding it, so I'm copying it here for easier future access:_

>We currently don't take advantage of the CollaborativeList. We could implement true array support by making the hasMany collections take advantage of them. I don't know how we would specifically architect it but it is something to look into.

>Currently our hasMany relationships are a plain array of integers. Every time something changes, the entire hasMany relationship gets replaced, which could get inefficient for larger lists.

>https://developers.google.com/drive/realtime/reference/gapi.drive.realtime.CollaborativeList

>Low priority.

**Comment by venkatd** [comment]
Thank you for looking into this thoroughly. Let us close this since, as you point out, there is no real benefit for the added complexity and effort.

**Comment by begedin** [comment]
OK, I'll close this. 

However, since we're abandoning the concept, I could also make sure it isn't used and then also get rid of anything related to `CollaborativeList` in the addon. Mainly, this is now in the `addon/lib/list-reference` file, but there's related code in `map-reference` as well.

Task #35 was created for this purpose.
