### ISSUE TITLE
Should storypad's document permissions also be part of ember-gdrive?

### ISSUE THREAD

**Issue by begedin** [coderly/ember-gdrive#34]
I'm primarily talking about the `gdrive-permissions` adapter and model we have in Storypad, but I guess transforming the `share-modal` functionality into a component and moving it to `ember-gdrive` is also possible.

Of course, custom e-mails could be an issue in that case, but there's nothing stopping us from adding a few configuration properties into the`ember-gdrive` configuration object to handle that, once it's implemented.

This is just something that crossed my mind, so I thought I'd write it down as a question, since it's something I'm bound to come across again.

**Comment by venkatd** [comment]
Yeah it would be good to move this into gdrive eventually since it isn't specific to storypad except the email delivery implementation.

**Comment by begedin** [comment]
In that case, I'm closing this and creating a new issue for moving stuff into ember-gdrive. New issue: #36.
