### ISSUE TITLE
Move actual permission logic from the share-modal component into a library

### ISSUE THREAD

**Issue by begedin** [coderly/ember-gdrive#41]
This can be done once #36 is resolved.

With "actual permission logic", I'm actually referring to the `share`, `removePermission` and `loadData` methods.

**Comment by begedin** [comment]
Just an FYI, this is simply a code quality improvement and probably isn't very urgent at the moment.

**Comment by begedin** [comment]
I went and gave this a try, but it turns out there's pretty much no gain out of moving the logic into a separate file. Most of the logic related to this actually is actually in the success/failure handlers after the operation is already done. We would basically just be duplicating the code for very little gain.

If at some point we require sharing/unsharing functionality in some other place, then it would make sense to move it into a library, but for now, I'm closing this, since it would more complicate things than make them simpler.

**Comment by venkatd** [comment]
Okay makes sense.
