### ISSUE TITLE
Eliminate the need to specify authentication type during authentication

### ISSUE THREAD

**Issue by begedin** [coderly/ember-gdrive#55]
By default, `ember-simple-auth` requires the authenticator to be specified while calling `session.authenticate`:

```
this.session.authenticate('authenticator:gdrive', {
  userID: userID
});
```

Since `ember-gdrive` makes use of `ember-simple-auth` for a specific type of authentication and the authenticator is always the same, it would make sense to eliminate this need.

I'm not at the moment sure if this is doable by specifying some `ember-simple-auth` setting, or if it requires modifying the session, but i think it's worth investigating.

**Comment by begedin** [comment]
@venkatd 

I've been thinking about this.

What if we simply move the code from the app into the add-on? Here's what we have:

In `storypad\app\routes\index.js`, we have the following code:
```
    this._super(transition);

    var route = this;
    var documentSource = route.get('documentSource');
    var state = documentSource.get('state'); // Forces creation of the state, which clears the query params
    var isStatePresent = state.get('isOpen') || state.get('isCreate');

    if (!isStatePresent) {
      return;
    }

    this.get('session').authenticate('authenticator:gdrive').then(function () {

      if (state.get('isOpen')) {
        return documentSource.openFromState();
      } else {
        return documentSource.createFromState();
      }
    }).then(function (doc) {
      if (doc) {
        route.transitionTo('document', doc);
      }
    });
  },

  actions: {
    login: function () {
      this.session.authenticate('authenticator:gdrive');
    }
  }
```

This is something that isn't app-specific, so it could be made a mixin.

In `storypad\app\routes\application.js`, we have: 
```
  actions: {
    logout: function () {
      var route = this,
        session = this.get('session');

      session.invalidate().then(function () {
        route.transitionTo('login');
      });
    }
  }
```

This can be made part of the `ApplicationRotueMixin` since again, none of the code is really 'application specific'.

And lastly, we have the following in `storypad\app\routes\login.js`:
```
actions: {
    login: function() {
      this.session.authenticate('authenticator:gdrive');
    }
  }
```

For this last case, `ember-simple-auth` has a `LoginControllerMixin` defined, [in which we can specify the default authenticator and then use that](https://github.com/simplabs/ember-simple-auth/tree/master/packages/ember-simple-auth-devise#the-authenticator). We could extend that mixin in `ember-gdrive` and then modify the app to handle logging in from the controller instead of the route.

If we do all of those, the actual authenticator name will never have to be mentioned within the app and authentication and document loading should be near-automatic everywhere except in the login controller, where we will simply bind a button to the `authenticate` action of the provided controller. We could even extend the mixin so the action will continue to be named `login`.

Your thoughts on this?

**Comment by begedin** [comment]
Note that implementing these changes wouldn't necessarily prevent the user from customizing the process to their own liking. They could always override the mixin actions and methods with their own.

**Comment by venkatd** [comment]
I think this is a really good idea. All for it. Reduces the complexity the user has to deal with by a lot.
