### ISSUE TITLE
Add ability to create a document through the graphical interface

### ISSUE THREAD

**Issue by begedin** [coderly/ember-gdrive#62]
Currently, we have to rely on a query string with JSON parameters to create and access a new document. Ideally, at least for testing, I believe `ember-gdrive` should provide an option to create such a document automatically.

**Comment by venkatd** [comment]
Could you elaborate on this?

**Comment by begedin** [comment]
Currently, the only way to create a document and start using the app is to access 

`http://[APP_URL_HERE]?state=%7B%22folderId%22:%22[FOLDER_ID_HERE]%22,%22action%22:%22create%22,%22userId%22:%22[USER_ID_HERE]%22%7D`

I'm thinking we add an action to the `ApplicationRouteMixin` which creates a new document and transitions to it, without the need for a special URL query string.

**Comment by venkatd** [comment]
Ok I agree with this. So then on the index page if you just navigate to the root domain name, you could potentially have a button to create a new document? This sounds like a good idea. I'm all for it.
