### ISSUE TITLE
Users accessing the document with no rights to access it should get an error

### ISSUE THREAD

**Issue by begedin** [coderly/ember-gdrive#64]
Something for the future. 

Accessing a document link with a user who doesn't have access to the document simply throws a console error, with no notification to the user.

**Comment by begedin** [comment]
@venkatd: How should the application behave in this case? An alert pop-up or something more advanced than that?

I realize it's probably not urgent, though.

**Comment by venkatd** [comment]
For now an alert should be sufficient but we can create an issue to do it in a more user-friendly way. For example, we could have a button to request access or switch accounts if they are using the wrong account.
