### ISSUE TITLE
Switch to .scss

### ISSUE THREAD

**Issue by begedin** [coderly/ember-gdrive#74]
Though the styling for the two built-in components is minimal, it has still gotten quite complex and has a good chance of getting even more complex. We should probably switch to .scss and add a preprocessing task sooner rather than later.

**Comment by begedin** [comment]
After digging through this, it's not as simple as it seems.

The easy approach would be to use `ember-cli-sass` and import the `.scss` as demonstrated in https://github.com/tylergaw/ember-cli-chartist/blob/master/index.js.

The slightly less easy way is to use broccoli-sass directly, the way Storypad does it in Brocfile.js.

In both cases, the issue is that it forces another dependency on the app, not the add-on itself. For now, I think sticking with .css is best, though the .css should be made simpler, as described in #78.

**Comment by begedin** [comment]
@venkatd: I've closed this, but if you think .scss could be worth the trouble, let me know and I'll reopen it.

**Comment by venkatd** [comment]
I think it's not worth it for now. We can try to organize the css as a second best option. I don't see there being too much css given that currently it is only the share modal that we need to style. Am I correct?

**Comment by begedin** [comment]
You are correct. There's only the share modal, though we might want to add some basic styles for the document-creator component as well.

A good thing is that I believe we are still able to split styles into several files, even though we aren't using .scss.

**Comment by venkatd** [comment]
That sounds fine to me. I think we have a manageable amount of css which means we can postpone this decision.
