### ISSUE TITLE
Make share-modal styles less specific if possible

### ISSUE THREAD

**Issue by begedin** [coderly/ember-gdrive#78]
Depending on the app that's using the addon, the share-modal styles might end up being too specific and a bit difficult to override.

We should consider making them less specific where possible. Methods of doing this:

* Reduce nesting of classes
* Make the root wrapper the component's tag name - > `share-modal`, instead of the class name we're currently using -> `.share-modal`. This way, the component can easily be overriden by the app by adding a custom class binding to it.

**Comment by begedin** [comment]
@venkatd: While a general reduction in css selector specificity would probably be an objective improvement, I'm not sure if you'd like me to go with using a class for the root selector, or the tag name of the element.

If the root selector is the class, then setting custom styles would be a matter of including the component in a template with a custom class specified:
```JavaScript
{{share-modal class="my-custom-class"}}. 
```
The original class would still end up on the resulting element, since the binding is still there, so we might have to worry about the specificity of original styles a bit more.

If we go with a `tagName` root selector, we would use
```JavaScript
{{share-modal tagName="my-custom-tag-name"}}. 
```

This way, there's no having to worry about original styles, but there would be an issue of the addon user potentially breaking layout by using an existing tag name such as a list item, an input or an anchor. Hopefully the chances of this are slim, but still...

**Comment by venkatd** [comment]
Sounds fine to me and a pretty small change to. I'm all for it.

**Comment by begedin** [comment]
Ok, I'll go with the tag name as the basic style selector then? Did I understand you correctly?

**Comment by venkatd** [comment]
Yeah you did.
