### ISSUE TITLE
Add missing and remove redundant dependencies

### ISSUE THREAD

**Issue by begedin** [coderly/ember-gdrive#79]
We've implemented auto-adding of ember-simple-auth and ember-cli-simple-auth during the addon installation process, but the reality is, those aren't the only dependencies. It's just that  usually, an ember app already has the other dependencies installed.

# Here's what's currently in bower.json

* "handlebars": "~1.3.0",
* "jquery": "^1.11.1",
* "ember": "1.8.1",
* "ember-data": "1.0.0-beta.12",
* "ember-resolver": "~0.1.11",
* "loader.js": "ember-cli/loader.js#1.0.1",
* "ember-cli-shims": "ember-cli/ember-cli-shims#0.0.3",
* "ember-cli-test-loader": "rwjblue/ember-cli-test-loader#0.0.4",
* "ember-load-initializers": "ember-cli/ember-load-initializers#0.0.2",
* "ember-qunit": "0.1.8",
* "ember-qunit-notifications": "0.0.4",
* "qunit": "~1.15.0"

# Here's what's currently in package.json

* "broccoli-asset-rev": "^2.0.0",
* "broccoli-ember-hbs-template-compiler": "^1.6.1",
* "ember-cli": "0.1.7",
* "ember-cli-content-security-policy": "0.3.0",
* "ember-cli-dependency-checker": "0.0.7",
* "ember-cli-6to5": "0.2.1",
* "ember-cli-ic-ajax": "0.1.1",
* "ember-cli-inject-live-reload": "^1.3.0",
* "ember-cli-simple-auth": "^0.7.1",
* "ember-cli-qunit": "0.1.2",
* "ember-data": "1.0.0-beta.12",
* "ember-export-application-global": "^1.0.0",
* "express": "^4.8.5",
* "glob": "^4.0.5"

Obviously, not all of these should be auto-added. Some are already part of a normal ember-cli app and  it's impossible for them to not be present. Some might not actually be necessary at all, so that should probably be checked as well.

@venkatd: I'm also thinking `handlebars` specifically should be replaced with `htmlbars`, like we did in Storypad, but I'm thinking that should probably be a separate task. Thoughts?

**Comment by venkatd** [comment]
@begedin if `ember-gdrive` requires `htmlbars` then I think it makes sense. Otherwise, what is the purpose? I can't think of a case where an Ember app wouldn't have one of the two installed.

**Comment by begedin** [comment]
@venkatd: I was actually thinking handlebars 2.0. Don't know why I wrote htmlbars.

However, I do believe both ember and ember-cli are gradually switching over to htmlbars and the upgrade to handlebars 2.0 is part of that gradual switch.

In any case, I was talking about handlebars 2.0. Should I make a task for that?

**Comment by venkatd** [comment]
Yeah that sounds fine.

**Comment by begedin** [comment]
There's no pull request yet, but here's the logic I'm following:

**If a dependency is part of the standard set of dependencies for an Ember-cli application, then the add-on should not have to install it manually - it's expected that it's already there.**

Based on that, the only npm package we need to install with the add-on is `ember-cli-simple-auth`, so that part is done. I'm not actually certain we even need to have it as an add-on dependency. Having the blueprint install it with the app might be enough.

As for bower components, following the same logic we get that nothing else is actually needed. The add-on does expect `ember-simple-auth` installed with the app, but it's not actually the add-on's dependency. 

So I guess I was a bit too pessimistic with the situation and the add-on is actually already very lean and up to date. There are only two things we need to do - one is to remove `ember-cli-simple-auth` from the add-on's dependencies if it isn't required and the other is to create a task for updating handlebars to 2.0 - #92.
