### ISSUE TITLE
Prevent user from revoking their own access right to the document

### ISSUE THREAD

**Issue by begedin** [coderly/ember-gdrive#85]
We're able to at least attempt revoking access right to our own document, including when we're the last user with access rights to it. There isn't anything on our side preventing the user from doing so. 

Google's API will probably throw some sort of error, but there probably should be some indicator on our side that we aren't supposed to do that.

@venkatd How far should we go with this? 

* Change the style of our own permission in the share-modal permission list? 
* Don't change the style, but disable the action? 
* **Display a message upon attempting to delete our  own permission?** _-this is the option we decided to go with_
* Not display our own permission at all?

**Comment by venkatd** [comment]
I think the 3rd option is the best. If it is disabled, then the user has no feedback or explanation.. "why couldn't I revoke my permission" .. which could lead to frustration.

The 4th option is interesting also but I think in some cases they might want to view what permission they have with relation to the document. For example, they may see that they only have read access once we implement that.

I think we should go with the 3rd option. Thoughts?
